name: gcc_pythonworkshop
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - xarray
  - scipy
  - cartopy
  - matplotlib
  - pip
  - jupyter
  - ipykernel
  - pip:
      - earthaccess
# how to use:
# conda env create -f environment.yml
# conda activate gcc_pythonworkshop
